var UserLang = {
Main_Selling_Unit:"وحدة البيع الرئيسية",
Customers_Sales_And_Debt_Report:"تقرير مبيعات ومديونيات العملاء",
Symbol:"الرمز",
In_Case_Of_Invoice_Outside_The_Registered_Distribution_Areas:"في حالة الفاتورة خارج مناطق التوزيع المسجلة",
Distribution_Area_Symbol:"رمز منطقة التوزيع",
Serial_Number_Starts_From:"الرقم المسلسل يبدا من",
All_The_Company_Works_On_A_Single_Serial_Number_System_For_All_Distribution_Areas:"كل الشركة تعمل علي نظام رقم مسلسل واحد لكل المناطق التوزيع",
Control_Orders_Serial_Settings:"التحكم في اعدادات سيرال الفواتير",
Direct_Exchange_Authorization_For_The_Customer:"اذن صرف مباشر للعميل",
Creation_Date:"تاريخ الإنشاء",
Excution_Date:"تاريخ التنفيذ",
Actions_Count:"عدد الإجراءات",
Vehicles_Stores_Limit_Exceeded:"عدد المركبات او المخازن وصل للحد الاقصي",
Users_Limit_Exceeded:"عدد المستخدمين وصل للحد الاقصي",
Other_Accounts:"حسابات اخري",
Purchase_Avg_Price:"متوسط سعر الشراء",
Sales_Avg_Price:"متوسط سعر البيع",
Users_Actions_Statistics_Report:"تقرير احصائيات اجراءات المستخدمين",
Products_Has_No_Category:"اصناف ليس لها فئات",
Products_Transactions_Inside_The_Vehicle_Report:"تقرير حركة الاصناف داخل المركبة / مخزن",
Stocktaking_Inventory_Report:"تقرير الجرد المخزني",
Cannot_Transfer_Stock_Not_Available:"لا يمكن نقل المخزون غير متوفر",
Stock_Cannot_Be_Transferred_In_Case_The_Balance_Is_Insufficient:"لايمكن نقل المخزون في الحالة الرصيد غير كافي",
Draft_Orders:"الفواتير المحفوظه مؤقتا",
Show_Product_Note_In_Customer_Order:"اظهار ملاحظه الصنف اثناء انشاء فاتورة العميل",
Product_Note:"ملاحظه الصنف",
More_Selected_Gifts_Than_Allowed:"هدايا مختارة اكثر من المسموح",
The_Maximum_Number_Of_Gifts_Can_Be_Chosen:"اقصي عدد يمكن اختيارة من الهدايا",
Total_Selected_Product_Count_in_Category:"اجمالي اعداد الاصناف المختارة داخل الفئة",
Over_Weight:"زيادة الوزن",
Close_Customer_Order_In_Exact_Weight:"اغلاق الفاتورة عند وزن معين",
Customer_Total_Points_SMS_Message:"نموذج رسالة باجمالي نقاط العميل",
Send_SMS_To_Customer_With_Total_Points:"ارسل رسالة باجمالي نقاط العميل",
Customers_Points_Report:"تقرير نقاط العملاء",
Send_Customer_Points_SMS_After_Order:"ارسل رسالة بنقاط العميل بعد كل فاتورة",
Customer_Points_SMS_Message:"نموذج رسالة النقاط للعميل",
Marketing_Material_Prices:"أسعار المواد التسويقية",
Marketing_Materials:"منتجات تسويقية",
Another_Executor_For_The_Order:"منفذ آخر للفاتورة",
Can_Change_Customer_Order_Creator:"يمكنه تغير منفذ فاتورة العميل",
Other_Mobiles_Numbers:"لارقام موبيل اخري",
Marketing_Messages:"الرسائل التسويقية",
The_Message_Will_Be_Sent_In_A_Name:"سيتم إرسال الرسالة بإسم",
Enter_Mobiles_Numbers:"ادخل ارقام المحمول المراد ارسال الرسالة لهم",
Send_Now:"ارسل الان",
The_Text_Of_The_Message:"نص الرسالة",
Marketing_Messages_To_Clients:"رسائل تسويقية للعملاء",
Points_Discounted_Due_To_Return:"النقاط المخصومه بسبب المرتجع",
Points_Balance:"رصيد النقاط",
Initial_Points_Balance:"رصيد النقاط الافتتاحي",
Total_Order_Points:"اجمالي نقاط الفاتورة",
New_Customer_Direct_Discount:"إضافة خصم مباشر للعميل",
Direct_Discount:"خصم مباشر",
Show_The_Product_Tax_In_The_Invoice_A_Value_Not_A_Percentage:"اظهار ضريبة الصنف في الفاتورة بقيمة وليس نسبة مئوية",
Products_Sales_Report_Products_Users:"تقرير مبيعات الاصناف (أصناف/مستخدم)",
Select_By_Product_Category:"الاختيار بفئة الصنف",
Select_By_Product_Name:"الاختيار باسم الصنف",
Need_To_Approval_When_Adding_New_Customer:"بحاجة إلى الموافقة عند إضافة عميل جديد",
Total_Assigned_Values:"اجمالي القيم الموزعة",
Adding_Customers_Report:"تقرير اضافات العملاء",
Adding_New_Customers_From_Type:"اضافة عملاء جدد من نوع",
Adding_New_Customers:"اضافة عملاء جدد",
Edit_Product_Tax_In_Customer_Order:"تعديل ضريبة الصنف داخل فاتورة العميل",
Final_Price:"السعر النهائي",
The_Sale_Price_Is_Lower_Than_Default_Supply_Price:"سعر البيع أقل من سعر التوريد الافتراضي",
Cannot_Make_Order_When_Found_Scheduled_Post_Poned:"لايمكن انشاء اي فاتورة في حالة وجود تحصيلات مؤجلة",
The_Number_Per_Unit:"العدد بالنسبة للوحده",
Points:"النقاط",
Main_Unit:"الوحده  الرئيسيه",
Doubling:"المضاغف",
The_Doubling_Number_Of_The_Main_Unit:"العدد المضاعف للوحده الرئيسيه",
Add_Doubling_To_The_Main_Unit:"اضافة مضاعفة للوحده الرئيسيه",
Total_Weights:"اجمالي الاوزان",
Weight:"الوزن",
The_Number_To_Be_Confirmed_Received_From_Stock:"عدد المطلوب تأكيد استلامه من المخزون",
Confirm_Stock_Receipt:"تأكيد استلام المخزون",
Action_Moving_Stock_Not_Completed_Need_Confirm_Received:"لن يتم نقل المخزون حتي تاكيد الاستلام",
Need_To_Confirm_When_Moving_Stock:"بحاجة إلى تأكيد عند نقل المخزون",
Delayed:"أجل",
Arabic_Plural_Groups:"مائة, ألف, مليون, مليار, تريليون, كوادريليون, كوينتليون, سكستيليون",
ArabicTwos:"مئتان, ألفان, مليونان, ملياران, تريليونان, كوادريليونان, كوينتليونان, سكستيليونان",
Arabic_Hundreds:", مائة, مئتان, ثلاثمائة, أربعمائة, خمسمائة, ستمائة, سبعمائة, ثمانمائة,تسعمائة",
Arabic_Tens:"عشرون, ثلاثون, أربعون, خمسون, ستون, سبعون, ثمانون, تسعون",
Arabic_Feminine_Ones:", إحدى, اثنتان, ثلاث, أربع, خمس, ست, سبع, ثمان, تسع,عشر, إحدى عشرة, اثنتا عشرة, ثلاث عشرة, أربع عشرة, خمس عشرة, ست عشرة, سبع عشرة, ثماني عشرة, تسع عشرة",
Arabic_Ones:", واحد, اثنان, ثلاثة, أربعة, خمسة, ستة, سبعة, ثمانية, تسعة,عشرة, أحد عشر, اثنا عشر, ثلاثة عشر, أربعة عشر, خمسة عشر, ستة عشر, سبعة عشر, ثمانية عشر, تسعة عشر",
Arabic_Suffix_Text:"لا غير.",
Arabic_Appended_Twos:"مئتا,ألفا, مليونا, مليارا, تريليونا, كوادريليونا, كوينتليونا,سكستيليونا",
Arabic_Group:"مائة, ألف,مليون, مليار, تريليون, كوادريليون, كوينتليون, سكستيليون",
Arabic_Appended_Group:", ألفاً,مليوناً, ملياراً, تريليوناً, كوادريليوناً, كوينتليوناً,سكستيليوناً",
English_Ones:"Zero, One, Two,Three, Four, Five, Six, Seven, Eight, Nine, Ten,Eleven, Twelve, Thirteen, Fourteen, Fifteen, Sixteen,Seventeen, Eighteen, Nineteen",
English_Tens:"Twenty,Thirty,Forty,Fifty,Sixty,Seventy,Eighty,Ninety",
English_Group:"Hundred,Thousand, Million, Billion, Trillion, Quadrillion,Quintillion, Sextillian, Septillion, Octillion,Nonillion, Decillion, Undecillion, Duodecillion,Tredecillion, Quattuordecillion, Quindecillion,Sexdecillion, Septendecillion, Octodecillion,Novemdecillion, Vigintillion, Unvigintillion,Duovigintillion, 10^72,10^75,10^78,10^81,10^84,10^87,Vigintinonillion,10^93,10^96,Duotrigintillion,Trestrigintillion",
English_Suffix_Text:"only.;",
Arabic_Prefix_Text:"فقط",
Egypt_Pound:"جنية مصرى",
Kersh:"قرش",
When_Save_Credence_Will_Add_Total_Confirmed_Discounts_In_Customer_Account:"عند حفط الاعتماد يتم اضافة قيمة الخصومات المعتمده الي حساب العميل",
Segment_Discount:"خصم الشريحة",
Other_Discounts:"خصومات اخري",
Add_Credence_Value_To_Customer_Account:"اضف قيمة الاعتماد الى حساب العميل",
Credence_Value:"قيمة الاعتماد",
The_Chip_Discount_Is_Not_Calculated:"عدم احتساب خصم الشريحة",
Customer_Segment_Based_On_Withdrawals_After_Tax:"شريحة العميل بناء علي المسحوبات بعد خصم الضريبة",
Total_Confirmed_Discounts:"اجمالي الخصومات التي تم احتسابها",
Customer_Withdrawals_Not_Match_Any_Segment:"مسحوبات العميل لا تناسب اي شريحة",
Tax:"الضريبة",
Credence_Cannot_Be_Compleated:"لايمكن اتمام الاعتماد",
Last_Credences:"الاعتمادات السابقة",
Based_On_The_Terms_Of_The_Contract:"بناء علي بنود العقد",
Credence_Date:"تاريخ الاعتماد",
Credence_Details:"تفاصيل الاعتماد",
New_Credence:"اعتماد جديد",
Customer_Withdrawals_From_The_Last_Credences_Date_After_Tax_Deduction:"مسحوبات العميل من تاريخ آخر اعتمادات بعد خصم الضريبة",
The_Date_Of_The_Last_Credenc:"تاريخ آخر اعتماد",
Customer_Withdrawals_From_The_Date_Of_The_Last_Credence:"مسحوبات العميل من تاريخ آخر اعتماد",
Credences:"الاعتمادات",
Contracts_Credences:"اعتمادات العقود",
Contract_Terms_Based_On_Other_Conditions:"بنود العقد بناء علي شروط اخري ",
The_Terms_Of_The_Contract_Are_Based_On_The_Withdrawals_During_The_Period:"بنود العقد علي حسب المسحوبات خلال الفتره ",
Withdrawals:"مسحوبات",
Accredited_Contracts:"التعاقدات الاعتمادية",
Accredited_Contract:"تعاقد اعتمادي",
Accredited_Contract_Details:"بيانات العقد الاعتمادي",
Upload_Image:"رفع صورة",
Communicate_With_Users:"التواصل مع المستخدمين",
Sending_Automatic_SMS_Messages_To_Admin_When_The_Clients_Debts_Are_Due_To_Be_Paid:"إرسال رسائل SMS تلقائية إلى الادمن  عند استحقاق سداد العملاء المدينين",
Sending_Automatic_SMS_Messages_To_Users_When_The_Clients_Debts_Are_Due_To_Be_Paid_According_To_The_Track:"إرسال رسائل SMS تلقائية إلى المستخدمين  عند استحقاق سداد العملاء المدينين طبقا لخط السير",
Automatic_SMS_Sending_To_Debtor_Customers_When_Payment_Is_Due:"إرسال رسائل SMS تلقائيًا إلى العملاء المدينين عند استحقاق السداد",
Number_To_Be_Collected_Today:"عدد المطلوب تحصيله اليوم",
Scheduled_Postponed:"جدول التحصيلات",
subscribed_In_Actions_Module:"مشترك في الاجراءات",
Cannot_Make_Payments_With_Minus_Value:"لا يمكن إجراء المدفوعات بالسالب",
Can_Make_Payments_With_Minus_Value:"يمكن إجراء المدفوعات بالسالب",
Fire:"تنفيذ",
Action_Was_Not_Implemented:"إجراء لم ينفذ",
Action_Is_Failed:"إجراء غير ناجح",
Action_Is_Succeeded:"إجراء ناجح",
Action_Status:"حالة الإجراء",
is_Action_Succeeded:"هل نجح الإجراء",
Must_Set_Action_Date_Time:"يجب تحديد وقت تاريخ الإجراء",
Previous_Balance:"الرصيد السابق",
The_Percentage_Of_Debt_Reaching_The_Credit_Limit:"نسبة وصول المديونية الي  الحد الائتماني",
Column_Name:"اسم العمود",
Debtors_Customers_Report_Settings:"اعدادات تقرير مديونيات العملاء",
My_Credit_Page_Settings:"اعدادات صفحة رصيدي",
Deleted_Orders:"المبيعات المحذوفة",
Deleted_Payments:"المدفوعات المحذوفة",
Deleted_Items:"المحذوفات",
Adjustments_Recorded:"التعديلات المسجلة",
Can_Sell_Unpriced_Product:"مسموح ببيع صنف غير مسعر",
Unpriced_Product:"صنف غير مسعر",
Not_Enough_Stock_For_Sale:"كمية مخزون غير كاف للبيع",
Can_Make_Order_With_Negative_Stock:"مسموح بالبيع المخزون بالسالب",
Control_Orders_Wayes:"التحكم في طريقة البيع",
Planning_Date:"تاريخ التخطيط",
Item_Column_Name_Settings:"اعدادات اسماء اعمدة الاصناف",
Arrange_Column:"ترتيب العمود",
View_Column:"اظهار العمود",
Column_Name_While_Printing:"اسم العمود اثناء الطباعة",
Default_Column_Name:"اسم العمود الافتراضي",
Automatic_Apply_Of_All_Invoices:"تطبيق تلقائي لجميع الفواتير",
New_Additions:"اضافة جديدة",
Additions_To_The_Customer_Order:"اضافات علي فاتورة العميل",
Signature_While_Invoices:"توقيع العميل اثناء الفواتير",
Signature_While_Payment:"توقيع العميل اثناء المدفوعات",
SMS_Sender_Name:"ارسال ال sms بإسم",
Payment_Rest_Template:"نموذج ايصال استلام نقدية",
Multiple:"متعدد",
CheckBox:"صح/خطأ",
Text:"نص",
Action_Details:"تفاصيل الإجراء",
Action_Type_Details:"تفاصيل نوع الإجراء",
Data_Type:"نوع البيانات",
Data:"البيانات",
Targeted:"المستهدف",
Action_Type:"نوع إجراء",
Action_Types:"نوع الإجراءات",
Action:"إجراء",
Actions:"الإجراءات",
Product_Prices_In_Previous_Orders:"اسعار الصنف في الفواتير السابقة لنفس العميل",
The_Maximum_Frequency_Of_The_Offer_Within_The_Invoice:"اقصي تكرار للعرض داخل الفاتورة",
Add_Edite_Customers_Financial_Data:"اضافة او تعديل البيانات المالية للعميل",
Required_Supply_Delivery:"المطلوب تحميل /تسليم",
Required_Supply:"المطلوب تحميل",
Required_Delivery:"المطلوب تسليم",
Customers_Was_Selected:"عملاء تم اختيارهم",
Move_Customers_To_Another_Track:"تحويل العملاء الي خط سير اخر",
Products_Need_To_Supply:"اصناف مطلوب توريدها",
Tree_Branch_Details:"تفاصيل فرع الشجرة",
Branch_Inside_The_Expenses_Tree:"قسم داخل شجرة المصروفات",
Related_To:"تابع ل",
Expenses_Tree:"شجرة المصروفات",
Send_SMS_To_Debtor_Customers:"إرسال الرسائل القصيرة للعملاء المدينين",
Send_Custome_SMS_To_Users:"ارسال رسالة نصية (ٍSMS) للموظفين",
Send_SMS_To_Pay_Off_Customers_Debts:"ارسال رسالة نصية (ٍSMS) لسداد مديونية العملاء",
Customer_Order_Messages:"رسائل بعد كل فاتورة",
Wrong_Mobile_Number:"رقم موبيل غير صحيح",
Failed_When_Sending_SMS_Message_Please_Try_Again:"فشل في إرسال رسالة SMS ، يرجى إعادة المحاولة",
SMS_Messages_Sent_Successfully:"تم ارسال الرسالة بنجاح",
Send_A_Debt_Payment_Message_By_Sms_Now:"ارسل رسالة SMS لدفع الديون",
Customer_Debt_Payment_Messages:"رسائل دفع مديونية العملاء",
SMS_Messages_Settings:"اعدادات رسائل ال SMS",
Recalculate_Target:"إعادة حساب الهدف",
My_Credit:"رصيدي",
Payments_Count:"عدد مرات المدفوعات",
Payments_Value:"قيمة المدفوعات",
Oreders_Count:"عدد الفواتير",
Month_Sales:"مبيعات الشهر",
Month:"الشهر",
Sent_SMSs_Report:"تقرير رسائل ال sms المرسلة",
SMSs:"رسائل ال sms",
Messages_Count:"عدد الرسائل",
Send:"أرسل",
Message:"الرسالة",
Add_Negative_Customer_Payment:"إضافة دفع العملاء بقيمة سالبة",
The_Advantages_Of_This_Type_Of_Customer:"المزايا التي يتمع بها هذا النوع من العملاء",
Based_On_The_Total_Purchases_Of_Specific_Items_During_The_Month:"بناء علي اجمالي مشتريات اصناف محددة خلال الشهر",
Based_On_Total_Purchases_During_The_Month:"بناء علي اجمالي المشتريات خلال الشهر",
Conditions_And_Benefits:"الشروط والمزايا",
Conditions_That_Must_Be_Met_By_The_Customer_To_Reach_This_Type:"الشروط الواجب توافرها للعميل للوصول لهذا النوع",
Product_Unit_Details:"تفاصيل وحدة الصنف",
Product_Unit:"وحدة صنف",
Product_Units:"وحدات الصنف",
Switch_View:"تبديل طريقة العرض",
Customers_Payments_Count:"عدد دفعات العملاء",
Current_Cash:"النقدية الحالية",
Delivery_Of_Custody_Is_Greater_Than_Available_With:"تسليم عهدة اكبر من المتاح مع ",
Users_Custodies_Report:"تقرير عهد المستخدمين",
Please_Select_User:"برجاء تحديد المستخدم",
Cannot_Transfer_Custody_To_Same_User:"لايمكن استلام العهده من مستخدم الى نفس المستخدم",
Receiving_Custody:"استلام عهدة",
Custodies:"العهد",
Custody:"عهدة",
Quantity_To_Be_Moved:"الكمية المراد نقلها",
Customer_Received_Cash:"العميل استلم نقدا",
Fine_On_Return_Invoices:"غرامة على فواتير المرتجع",
Total_Refund:"اجمالي المبغ المستحق استرداده",
No_Changes_To_Save:"لا توجد تغيرات للحفظ",
Quantity_Of_Retrun_Is_Greater_Than_Quantity_Purchased:"كمية مرتجعة اكبر من الكمية المشتراة",
Quantity_Of_Retrun_From_Type:"كمية المرتجع من نوع",
Return_Type:"نوع المرتجع",
Can_Not_Put_A_Visit_Less_Than_Minute:"لا يمكن للزيارة العميل ان تكون اقل من 1 دقيقة",
Official_Working_Days_Of_The_Company:"ايام العمل الرسمية للشركة",
The_Duration_Of_The_Visit_To_The_Customer_Per_Minute:"مدة الزيارة للعميل بالدقيقة تقريبا",
Select_A_Day:"حدد يوم",
Schedule_Of_Visits:"جدول الزيارات",
Affiliated_Users:"المستخدمين التابعين",
Do_You_Need_To_Continue:"هل تريد المتابعة؟",
Customer_Allready_Exist_In_Another_Track:"العميل موجود بالفعل في خط سير اخر: ",
Allowance:"المسموح به",
Friday:"الجمعة",
Thursday:"الخميس",
Wednesday:"الاربعاء",
Tuesday:"الثلاثاء",
Monday:"الاثنين",
Sunday:"الاحد",
Saturday:"السبت",
Visit_Times_From_To_Through_The_Day:"اوقات الزيارة من الى خلال اليوم",
Direct_Manager:"المدير المباشر",
The_Days_Of_The_Visit_Are_Available_To_The_Client_During_The_Week:"ايام الزيارة المتاحة للعميل خلال الاسبوع",
The_Number_Of_Visits_During_The_Month:"عدد مرات الزيارة خلال الشهر",
Custome_Visits:"الزيارات الخاصة بالعميل",
Indebtedness_Less_Than:"المديونية اصغر من",
Indebtedness_Greater_Than:"المديونية أكبر من",
Debtors_Customers:"العملاء المدينين",
Debtors_Customers_Report:"تقرير مديونيات العملاء",
Send_Email_To_Customer_After_Each_Invoice:"ارسال ايميل   للعميل بعد كل فاتورة",
Communicate_With_Customers_After_Each_Invoice:"التواصل مع العملاء بعد كل فاتورة",
Send_Sms_To_Customer_After_Each_Invoice:"ارسال رسالة نصية (ٍSMS) للعميل بعد كل فاتورة",
Communicate_With_Customers:"التواصل مع العملاء",
StockType:"نوع مخزون",
StockType_Details:"تفاصيل نوع المخزون",
StockTypes:"انواع المخزون",
Customers_Classificaions:"تصنيفات العملاء",
Invoice_Cannote_Completed_Postponed_Balance_Reach_The_Credit_Limit_Balance:"لا يمكن إكمال الفاتورة. الرصيد المؤجل وصل إلى حد الرصيد الائتماني",
The_Client_Indebtedness_Reached_The_Credit_Limit:"مديونية العميل وصلت للحد الائتماني",
Gain_Discounts_worth:"حصل علي خصومات بقيمة",
My_Targets:"أهدافي",
Discounts_For_Invoice:"الخصومات المستحقة للفاتورة",
percentage:"النسبة %",
Discount_Details:"تفاصيل الخصم",
Discounts:"الخصومات",
Track_Details:"تفاصيل خط السير",
Region_Details:"تفاصيل الإقليم",
Tracks:"خطوط السير",
Regions:"الأقاليم",
Depots:"القطاعات",
Depot_Details:"تفاصيل القطاع",
Region:"إقليم",
Depot:"قطاع",
Track:"خط سير",
Properties:"الخواص",
Responsibility:"المسؤلية",
The_Distribution_Of_Inputs_To_Staff_Is_Not_Equal_To_The_Total_Goal:"توزيع المدخلات على الموظفين غير متساوي مع اجمالي الهدف",
Full_Products_Stock_Report:"تقرير مخزون الاصناف الكامل",
Company_Target_Details:"تفاصيل الهدف",
Information_About_The_Target:"معلومات عن الهدف",
Achievement_Percentage:"نسبة المحقق",
Achievement:"المحقق",
Customer_Type_Details:"تفاصيل نوع العميل",
Customer_Type:"نوع العميل",
Customer_Types:"انواع العميل",
Credit_Time:"وقت الحد الإئتماني",
Responsible:"المسئول",
Product_Category_Total_Unit_Sales:"اجمالي مبيعات وحدات فئات اصناف",
Product_Units_Sales:"اجمالي مبيعات وحدات صنف",
Product_Category_Total_Sales:"اجمالي مبيعات فئة صنف",
Product_Total_Sales:"اجمالي مبيعات صنف",
Customer_Grade_Collected_Mony:"تحصيل من فئة عميل",
Customer_Collected_Mony:"تحصيل من عميل",
Customer_Grade_Sales:"مبيعات فئة عملاء",
Customer_Sales:"مبيعات عميل",
Collected_Mony:"التحصيل",
Target_Amount_To_Be_Collected:"المبلغ المستهدف تحصيله",
Target_Amount:"المبلغ المستهدف",
Target_Type:"نوع الهدف",
Target_Title:"عنوان الهدف",
Company_Target:"هدف للشركة",
Company_Targets:"أهداف الشركة",
Merchandising_Material:"مادة تسويقية",
Merchandising_Material_Details:"تفاصيل المادة التسويقية",
Merchandising_Materials:"مواد تسويقة",
Performance:"الاداء",
Offer:"عرض",
Search_For:"بحث عن",
Areas:"المناطق",
Price_Category_Details:"تفاصيل الفئة السعرية",
Outlet_Classification_Details:"تفاصيل تصنيف سوق",
Price_Categories:"الفئات السعرية",
Outlet_Classifications:"تصنيفات الأسواق",
Outlet_Classification:"تصنيف السوق",
Price_Category:"فئة سعرية",
Vehicles_Stores_Stock_Report_Vehicle_Store_Products:"تقرير مخزون المركبات/المخازن (مركبة-مخزن/أصناف)",
Vehicles_Stores_Stock_Detailed_Report:"تقرير مخزون مفصل للمركبات/المخازن ",
Products_Sales_Details_Report_User_Products:"تقرير مبيعات الاصناف (مستخدم/أصناف)",
Products_Sales_Details_Report_User_DistributionArea_Products:"تقرير مبيعات الاصناف (مستخدم/منطقة توزيع/أصناف)",
Products_Sales_Details_Report_User_Vehicle_Products:"تقرير مبيعات الاصناف (مستخدم/مركبة/أصناف)",
Sold:"المباع",
Returned:"مرتجع",
Offers_Sales_Report:"تقريرمبيعات العروض",
Distributions_Area:"مناطق التوزيع",
Distribution_Area_Sales_Report:"تقريرمبيعات منطقة توزيع",
Maintenance_Deadline:"اخر ميعاد للصيانة",
Vehicle_Movements:"تحركات المركبة",
Less:"القليل",
More:"المزيد",
Has_Earned:"حصل علي",
Orders_That_Have_Benefited_From_The_Offer:"الطلبيات التي استفادت من العرض",
Information_About_The_Offer:"معلومات عن العرض",
Conditions_To_Be_Eligible_For_The_Offer:"الشروط التي توفرت لاستحقاق العرض",
Offer_Priority:"اولوية العرض",
Total_Invoice_Inside_Offer:"اجمالي الفاتورة داخل العرض",
Invalid_Customer_Signature:"توقيع العميل غير مطابق",
Please_Enter_Customer_Signature:"من فضلك ادخل توقيع العميل",
Offer_For_Invoice:"العرض المستحق للفاتورة",
Total_Order_And_Discount:"اجمالي الفاتورة والخصم",
Selected_Products:"الأصناف التي تم اختيارها",
Recalculate_Source_Balanace:"إعادة حسابات المصدر",
Recalculate_Customer_Balanace:"إعادة حسابات العميل",
Total_Order_Price:"مجموع سعر الفاتورة",
Warning_There_Is_A_Duplicate_Product_In_This_Invoice_Do_You_Wish_To_Continue:"تحذير ، هناك منتج مكرر في هذه الفاتورة ، هل ترغب في المتابعة؟",
Warning_There_Is_One_Or_More_Products_Without_A_Price_Do_You_Wish_To_Continue:"تحذير ، هناك منتج واحد أو أكثر بدون سعر ، هل ترغب في المتابعة؟",
Frequency_Offer:"تكرار العرض",
Total_Order_Discount_Precentage:"خصم  مئوي على اجمالي الفاتورة",
Total_Order_Discount_Value:"خصم على اجمالي الفاتورة",
Free_Additional_Products:"منتجات اضافية مجانية",
Discount_On_Products:"خصم على أصناف",
Additional_Gifts:"هدايا اضافية",
Gifts:"الهدايا",
Conditions:"الشروط",
Exact_Customer:"عميل محدد",
Offer_Type:"نوع العرض",
End_Date:"تاريخ الانتهاء",
Start_Date:"تاريخ البدء",
Supplies_Detail:"تفاصيل التوريدات",
Distribution_Area_Details:"تفاصيل منطقة التوزيع",
Distribution_Areas:"مناطق التوزيع",
Distribution_Area:"منطقة توزيع",
Orders_Detail:"تفاصيل الفواتير",
Order_Detail:"تفاصيل الفاتورة",
Sales_Target:"اهداف المبيعات",
Marketing:"التسويق",
Sales:"المبيعات",
Governovate:"المحافظة",
Neighborhood:"الحي",
City:"المدينة",
Invoices_Only_By_Location:"الفواتير فقط بالمكان",
Customer_Signature:"توقيع العميل",
Payments:"المدفوعات",
Edit_Offer:"تعديل العرض ",
Offer_Details:"تفاصيل العرض",
New_Offer:"عرض جديد",
Offers:"العروض",
Number:"رقم",
Monitoring_Board:"لوحة المراقبة",
Stock:"مخزون",
Store:"مخزن",
Vehicle:"مركبة",
Allowed_Vehicles_Stores:"المركبات/المخازن المسموحة",
Category_Search:"بحث عن فئة",
Product_Category_Stock_Report:"تقرير مخزون فئة صنف",
Categories:"الفئات",
Product_Category_Profitability_Report:"تقرير ربحية فئة صنف",
Product_Profitability_Report:"تقرير ربحية صنف",
Product_Store_Profitability_Report:"تقرير ربحية صنف/مخزن",
Highest_Sold_Count_Products:"الاعلي مبيعات عددا",
Highest_Sold_Price_Products:"الاعلي مبيعات سعرا",
Difference:"الفرق",
Order_By:"الترتيب بـ",
Highest_Sold_Products:"اكثر الأصناف مبيعا",
Add_Return:"إضافة مرتجع",
Product_Category_Valuation_Report:"تقرير تقييم مخزون فئة صنف",
Customers_Orders:"مبيعات العملاء",
Sources_Supplies:"توريدات من المصادر",
Merge:"دمج بيانات",
Total_Profit:"إجمالي الربح",
Products_Statistics:"إحصائيات الأصناف",
Total_Orders_Price:"مجموع أسعار البيع",
Total_Supplies_Price:"مجموع أسعار التوريدات",
Sold_Units_Count:"عدد الوحدات المباعة",
Bought_Units_Count:"عدد الوحدات المشتراه",
Products_Count:"عدد الأصناف",
Is_Dual:"شريحتين؟",
Storage:"المساحة التخزينية (جيجا)",
Processor:"المعالج",
OS:"نظام التشغيل",
Color:"اللون",
Battery:"البطارية (ملي امبير)",
RAM:"رام (جيجا)",
Screen_Size:"حجم الشاشة (بوصة)",
Back_Camera:"الكاميرا الرئيسية (MP)",
Front_Camera:"الكاميرا الامامية (MP)",
Cash_Customer_Bill:"فاتورة لعميل نقدي",
Cash_Customer:"اسم العميل النقدي",
Google_Plus:"النشر في جوجل+",
Twitter:"النشر في تويتر",
Facebook:"النشر في فيس بوك",
Social_Media_Marketing:"نشر في وسائل التواصل الاجتماعي",
Copy:"نسخ",
Add:"إضافة",
Default_Supply_Price:"سعر التوريد الإفتراضي",
Fast_Add:"إضافة سريعة",
View:"مشاهدة",
Permisions:"الصلاحيات",
Edit_Order_Products_Prices:"تعديل اسعار الأصناف بالمبيعات",
Hide_Prices_Print:"إخفاء الاسعار في الطباعة",
Product_Type:"نوع الصنف",
Notifications_Settings:"إعدادات التنبيهات",
Customers_Notifications:"تنبيهات التعديلات بالعملاء",
Users_Notifications:"تنبيهات التعديلات بالمستخدمين",
Sources_Notifications:"تنبيهات التعديلات بالمصادر",
Products_Notifications:"تنبيهات التعديلات بالأصناف",
Vehicles_Stores_Notifications:"تنبيهات التعديلات بالمركبات/المخازن",
Product_Vehicles_Stores_Notifications:"تنبيهات مخزون المركبات/المخازن",
Customer_Orders_Notifications:"تنبيهات مبيعات العملاء",
Source_Supplies_Notifications:"تنبيهات توريدات المصادر",
Customer_Payements_Notifications:"تنبيهات مدفوعات العملاء",
Source_Payments_Notifications:"تنبيهات مدفوعات المصادر",
Expenses_Notifications:" تنبيهات المصاريف",
Product_Minimum_Qauntity_Supply_Notifications:"تنبيهات الحد الادني للتوريد",
Product_Orders:"مبيعات الصنف",
Product_Supplies:"توريدات الصنف",
Vehicle_Store_Selection_Is_Required:"لابد من إختيار مركبة/مخزن",
Old_Password:"كلمة السر القديمة",
Not_Valid:"غير مسموح بها",
New_Password:"كلمة السر الجديدة",
And:"و",
Or:"أو",
Not_Equal:"لا تساوي",
Change_Password:"تغيير كلمة السر",
Admin:"كامل الصلاحيات (ادمن)",
Is_Mandatory:"إجباري",
Are_You_Sure_Save_These_Products_Data:"هل تريد حقا حفظ بيانات الأصناف هذه؟",
Minimum_Qauntity_For_Supply_Data_Is_Not_Digits:"بيانات الحد الأدني للتوريد ليست أرقام",
System_Colors:"ألوان النظام",
Are_You_Sure_Save_These_Customers_Data:"هل تريد حقا حفظ بيانات العملاء هذه؟",
Are_You_Sure_Save_These_Sources_Data:"هل تريد حقا حفظ بيانات المصدر هذه؟",
Initial_Balance_Data_Is_Not_Digits:"بيانات الرصيد الإفتتاحي ليست أرقام",
Customer_Grade_Data_Is_Not_Valid:"بيانات فئة العميل ليست صحيحة",
Please_Select_One_Row_At_Least:"لابد من إختيار صف واحد علي الأقل",
Already_Exist:"موجود مسبقا",
The_Maximum_Data_Submitted_Are_500_Rows_Per_File:"الحد الأقصي للبيانات المرفوعة هي ٥٠٠ صف للملف الواحد",
Notice:"لاحظ",
Add_To_Customer_Order:"إضافة الي مبيعات عميل",
Add_To_Source_Supply:"إضافة إلي توريدات من مصدر",
Address:"العنوان",
Alerts:"تنبيهات",
All:"الكل",
All_Customers:"كل العملاء",
All_Products:"كل الأصناف",
All_Sources:"كل المصادر",
Are_You_Sure_Delete:"هل انت متأكد - لا يمكنك التراجع بعد الحذف",
Balance:"الاجمالي",
Barcode:"باركود",
Calculate:"احسب",
Can_Not_Be_Deleted:"لا يمكن حذفه",
Cancel:"إلغاء",
Category:"الفئة",
Chart:"رسم بياني",
Code:"الكود",
Company_Settings:"إعدادات الشركة",
Confirm:"تاكيد",
Confirm_Password:"تأكيد كلمة السر",
Confirmed_Visits:"زيارات مؤكدة",
Count:"العدد",
Customer:"عميل",
Customer_Details:"بيانات العميل",
User_Details:"بيانات المستخدم",
Customer_Financial_Data:"بيانات العميل المالية",
Customer_Financial_Summary:"ملخص حساب العميل",
Customer_Grade_Sales_Report:"تقريرمبيعات فئة عميل",
Customer_Not_Defined:"لم يتم تحديد العميل",
Customer_Order_Report:"تقرير مبيعات العملاء",
Products_In_Customer_Orders_Report:"تقرير أصناف بمبيعات العملاء",
Customer_Order_Template:"نموذج فاتورة العميل",
Customer_Orders:"مبيعات العميل",
Customer_Orders_Filters:"فلاتر مبيعات العميل",
Customer_Payments:"مدفوعات العميل",
Customer_Sales_Report:"تقريرمبيعات عميل",
Customers:"العملاء",
Customers_Payments:"مدفوعات العملاء",
Customers_Payments_Report:"تقرير مدفوعات العملاء",
Customers_Report:"تقرير العملاء",
Customers_Search:"بحث عن عميل",
Customers_Orders_Search:"بحث عن فاتورة",
Daily:"يومي",
Dashboard:"الرئيسية",
Data_Selection:"إختيار البيانات",
Data_Upload:"رفع بيانات",
Date:"تاريخ",
Delete:"حذف",
Deleted:"حذفت",
Description:"الوصف",
Details:"تفاصيل",
Discount:"خصم",
Does_Not_Exist:"غير موجود",
Edit:"تعديل",
Edit_Customer_Info:"تعديل بيانات العميل",
Edit_Source_Info:"تعديل بيانات المصدر",
Edit_User:"تعديل بيانات مستخدم",
Email:"البريد الإلكتروني",
Expense:"المصاريف",
Expense_Types:"نوع المصروف",
Expenses:"المصاريف",
Expenses_Report:"تقرير المصاريف",
Export:"تحميل بيانات",
File_No:"رقم الملف",
File_No_Allready_Exist:"رقم الملف محجوز",
File_Selection:"إختيار الملف",
File_Upload:"رفع الملف",
Files:"ملفات",
Search:"بحث",
Finance:"الحسابات",
Financial_Data:"البيانات المالية",
Financial_Report:"التقارير المالية",
From:"من",
From_Vehicle_Store:"من مركبة/مخزن",
Full_Access:"صلاحيات كاملة",
Full_Name:"الاسم الكامل",
Go_Back:"عودة للسابق",
Grade:"الفئة",
Has_Product:"به صنف",
Help:"مساعدة",
HR:"الموارد البشرية",
Image:"صورة",
Initial_Balance:"الرصيد الافتتاحي",
Invalid_User_Name_Or_Password:"اسم المستخدم أو كلمة السر غير صالحة",
Stocktaking:"جرد",
Inventory:"المخزون",
Invoices:"الفواتير",
Item:"صنف",
Job:"الوظيفة",
Language:"اللغة",
Loading_User_Data:"جاري تحميل بيانات المستخدم",
Location:"الموقع الجغرافي",
Credit_Limit:"حد الأئتمان",
Logo:"شعار الشركة",
logout:"خروج",
Main_Info:"معلومات اساسية",
Main_User_Data:"بيانات المستخدم الرئيسية",
Manufacturer_Part_Number:"الاسم التجاري بالمصنع",
Minimum_Qauntity_For_Supply:"حد أدني للتوريد",
Mobile:"موبايل",
Monthly:"شهري",
More_Info:"معلومات آخرى",
My_Account:"حسابي",
Name:"الاسم",
Name_Already_Exist:"الاسم موجود سابقا",
New_Customer:"عميل جديد",
New_Customer_Payment:"إضافة مدفوعات للعميل",
New_Expenses:"اضافة مصروف",
New_Order:"إضافة مبيعات جديدة",
New_Payment:"إضافة مدفوعات جديدة",
New_Product:"صنف جديد",
New_Supply:"توريدات جديدة",
New_Stock_Movement:"حركة نقل مخزون",
New_Vehicle_Store:"مركبة/مخزن جديدة",
New_Source:"مصدر جديد",
New_Source_Payment:"مدفوعات جديدة للمصدر",
New_User:"مستخدم جديد",
Next:"التالي",
No:"لا",
No_Data_Found:"لا توجد بيانات",
Notes:"ملاحظات",
Nothing_To_Search_For:"لا شيء للبحث عنه",
Orders:"المبيعات",
Orders_Count:"عدد المبيعات",
Orders_Report:"تقرير المبيعات",
Paid:"المدفوع",
Password:"كلمة السر",
Password_Is_Not_Confirmed:"كلمة السر غير مؤكدة",
Password_Must_Be_At_Least_4_Characters_Or_Letters:"كلمة السر يجب ان تكون 4 حروف على الاقل",
Payee:"المدفوع له",
Payments_Balance_Report:"تقرير المصاريف",
Please_Add_A_Content:"الرجاء إضافة المحتوى",
Please_Add_A_Name:"الرجاء إضافة الاسم",
Please_Add_A_Name_Price_And_Date:"الرجاء إضافة الاسم والسعر والتاريخ",
Please_Add_A_Username:"الرجاء إضافة اسم المستخدم",
Please_Review_Date_Input:"الرجاء مراجعة التاريخ",
Please_Add_A_Valid_Birthdate:"الرجاء إضافة تاريخ ميلاد صالح",
Please_Add_A_Valid_Password:"الرجاء اضافة كلمة مرور صالحة",
Please_Complete_The_Inputs:"الرجاء إكمال البيانات",
Please_Define_A_Valid_Date_Range:"الرجاء تحديد فترة تاريخ صالحة",
Please_Select_A_Product:"الرجاء اختيار صنف",
Please_Select_A_Quantity:"الرجاء إختيار الكمية",
Please_Select_A_Vehicle_Store:"الرجاء اختيار مركبة/مخزن",
Postponed:"مؤجل",
Prepaid:"المدفوع مسبقا",
Previous:"السابق",
Price:"السعر",
Price_A:"السعر الأول",
Price_B:"السعر الثاني",
Price_C:"السعر الثالث",
Price_D:"السعر الرابع",
Price_E:"السعر الخامس",
Price_Grades:"فئات الأسعار",
Prices:"الأسعار",
Prices_Offer_List:"قائمة عروض الاسعار",
Print:"طباعة",
Print_Preview:"أختبار الطباعة",
Printing_Settings:"إعدادات الطباعة",
Prints:"مطبوعات",
Product_Category_Sales_Supplies_Report:"تقريرمبيعات و توريدات فئة صنف",
Product_Details:"بيانات الصنف",
Product_Inventory:"مخزون الصنف",
Product_Inventory_Report:"تقرير مخزون صنف",
Product_Location:"موقع الصنف بالمركبة/المخزن",
Product_Name:"اسم الصنف",
Product_Sales_Supplies_Report:"تقريرمبيعات و توريدات صنف",
Product_Search:"بحث عن صنف",
Products:"الأصناف",
Vehicles_Stores_Has_Products:"الأصناف الموجودة بالمركبة/المخزن فقط؟",
Products_Report:"تقرير الأصناف",
Products_Without_Barcode:"أصناف بدون باركود",
Products_Without_Category:"أصناف بدون فئة",
Products_Without_Min_Quantity:"أصناف بدون حد أدني للتوريد",
Products_Without_Price:"أصناف بدون اسعار",
Products_Without_Stock:"أصناف بدون مخزون",
Profit_Report:"تقرير الأرباح",
Supply:"توريدات",
Supplies_Count:"عدد التوريدات",
Supplies_Report:"تقرير التوريدات",
Quantity:"الكمية",
Recent_Searchs:"اخر بحث",
Redirecting:"إعادة توجيه ...",
Report_Is_Ready:"التقرير جاهز",
Reports:"التقارير",
Sales_And_Supply:"مبيعات و توريدات",
Save:"حفظ",
Save_Account_Data:"حفظ بيانات الحساب",
Save_Draft:"حفظ مؤقت",
Save_Expense_Data:"حفظ المصروف",
Save_Print:"حفظ وطباعة",
Save_Print_Template_Data:"حفظ وطباعة بيانات النموذج",
Saved:"تم الحفظ",
Saved_Template:"النماذج المحفوظة",
Saving:"جارى الحفظ...",
Search_By_Name_File_No_Address_Job_Mobile_Gender_Etc:"البحث عن طريق الاسم، رقم الملف ,العنوان ,الوظيفة ,موبايل الخ ..",
Searching:"جاري البحث",
Select_A_Date_For_This_Visit:"برجاء تحديد موعد لهذه الزيارة",
Select_A_Date_In_The_Future:"برجاء تحديد تاريخ في المستقبل",
Serial:"رقم الفاتورة",
Serial_Prices_Are_Required:"الرجاء تحديد رقم الفاتورة و السعر",
Settings:"الإعدادات",
Shipment:"الشحن",
Soon:"حالاً",
Start_Hour:"ساعة البدء",
Statistics:"إحصائيات",
Status:"الحالة",
Stock_Lots:"دفعات المصدر",
Stock_Movement:"حركة نقل مخزون",
Stock_Movement_Filters:"تحديد حركات نقل مخزون",
Stock_Settings:"اوضاع المخزون",
Vehicle_Store_Details:"بيانات المركبة/المخزن",
Vehicle_Store_Name:"اسم المركبة/المخزن",
Vehicle_Store_Products:"الأصناف بالمركبة/المخزن",
Vehicle_Store_Sales_Supplies_Report:"تقريرمبيعات و توريدات مركبة/مخزن",
Vehicle_Store_Valuation_Report:"تقرير تقييم مركبة/مخزن",
Vehicles_Stores:"المركبات/المخازن",
Vehicle_Store:"مركبة/مخزن",
Vehicles_Stores_Search:"بحث عن مركبة/مخزن",
Summary:"ملخص",
Source:"مصدر",
Source_Details:"بيانات المصدر",
Source_Financial_Data:"بيانات المصدر المالية",
Source_Financial_Summary:"ملخص حساب المصدر",
Source_Not_Defined:"لم يتم تحديد المصدر",
Source_Payments:"مدفوعات للمصدر",
Source_Supplies_Report:"تقرير توريدات من مصدر",
Source_Supply_Template:"نموذج التوريد من مصدر",
Source_Supplies:"توريدات من مصدر",
Source_Supplies_Filters:"فلاتر التوريدات من المصادر",
Sources:"المصادر",
Sources_Payments:"مدفوعات للمصادر",
Sources_Payments_Report:"تقرير المدفوعات للمصادر",
Sources_Prices_Offers:"عروض أسعار المصادر",
Sources_Supplies_Report:"تقرير توريدات المصادر",
Sources_Report:"تقرير المصادر",
Sources_Search:"بحث عن مصدر",
Template:"نموذج",
Template_Contents:"محتويات النموذج",
Template_Keys:"مفاتيح النموذج",
Time:"التوقيت",
To:"إلى",
To_Vehicle_Store:"إلي مركبة/مخزن",
Total:"مجموع",
Total_Customers_Payments:"مجموع مدفوعات العملاء",
Total_Expenses:"مجموع المصاريف",
Total_Price:"السعر الإجمالي",
Total_Sources_Payments:"مجموع المدفوعات للمصادر",
Type:"نوع",
Unit:"الوحدة",
Units:"الوحدات",
Update_Customer:"تعديل بيانات عميل",
Update_Expense:"تعديل المصروف",
Update_Product:"تعديل بيانات الصنف",
Update_Product_Inventory:"تعديل مخزون صنف",
Update_Product_Prices:"تعديل أسعار الصنف",
Update_Vehicle_Store:"تعديل بيانات المركبة/المخزن",
Update_Source:"تعديل بيانات المصدر",
Update_User:"تعديل بيانات المستخدم",
Uploading:"جاري رفع الملف",
User_Name:"اسم المستخدم",
User_Privileges:"صلاحيات المستخدم",
User_Sales_Supplies_Report:"تقريرمبيعات و توريدات مستخدم",
Users:"المستخدمين",
User:"المستخدم",
Users_Search:"بحث عن مستخدم",
Users_Settings:"إعدادات المستخدمين",
Value:"القيمة",
Value_Can_Not_Be_More_Than:"القيمة لا يمكن ان تكون اكبر من ",
Value_Can_Not_Be_Zero_Or_Negative:"القيمة لا يمكن ان تكون صفر او اصغر",
Welcome:"مرحبا :",
Working_Please_Wait:"برجاء الانتظار.....",
Yes:"نعم",
You_Can_Not_Move_Stock_From_The_Same_Vehicle_Store:"لا يمكن نقل مخزون من نفس المركبة/المخزن",
You_Don_T_Have_A_Privileges_To_Access_This_Section:"أنت لا تملك امتيازات للوصول إلى هذا القسم",
Hierarchy:"الهيكل التنظيمي",
Visit_Day:"يوم الزيارة",
Cost_Price:"سعر التكلفة",
Contracts:"التعاقدات",
Contract:"تعاقد",
Contract_Details:"بيانات التعاقد",
Period:"الفترة",
Segment:"شريحه",
Segments:"الشرائح",
New_Segment:"شريحه جديدة",
Segment_Details:"بيانات الشريحه",
Cash:"نقدي",
Invoice_Segment:"شريحة الفاتورة",
Pay_In_Cash:"الدفع نقدي",
Id:"رقم المسلسل",
no_condition:"بدون شروط",
Not_Applicable:"غير مطبق",
Monthely_Customer_Purchases:"مسحوبات العميل الشهريه",
Contract_Terms:"بنود العقد",
New_Contract:"عقد جديد",
Due_Date:"تاريخ الاستحقاق",
Total_Invoice_Before_Discounts:"اجمالي الفاتورة قبل الخصم",
Total_Offers_Discounts:"اجمالي خصومات العروض",
Total_Discounts_amount:"اجمالي الخصومات علي الفاتورة",
Total_Segments_Discounts:"اجمالي خصومات الشرائح",
Discount_Not_Applied:"لم يتم تطبيق الخصم نظرا لعدم تحقق الشروط",
Now:" دفع فوري",
Mid_Year:"نصف سنوي",
End_Year:"نهايه العام",
Our_Prouducts:"منتجاتنا فقط",
Minimum_Sales_Month:"الحد الادني لمسحوبات العميل",
Periodical_Monthley_Sales:"مسحوبات شهريه منتظمه",
Total_Instant_Discounts_From_Contracts:"إجمالي الخصومات الفوريه من التعاقدات",
Quarter:"ربع سنوي",
Send_Customer_Financial_Report_Via_SMS:"ارسال رسالة نصية مؤقتة بتقرير بيانات العميل المالية",
Are_You_Sure:"هل انت متاكد",
Invalid_Customer_Mobile_Number:"رقم تليفون العميل غير صحيح",
First_Supply_Price:"سعر اول توريد",
Last_Supply_Price:"سعر اخر توريد",
Min_Supply_Price:"اقل سعر توريد",
Max_Supply_Price:"اكبر سعر توريد",
Supplies_Items_Count:"عدد الوحدات الموردة",
First_Order_Price:"سعر اول فاتورة",
Last_Order_Price:"سعر اخر فاتورة",
Min_Order_Price:"اقل سعر فاتورة",
Max_Order_Price:"اكبر سعر فاتورة",
Orders_Items_Count:"عدد الوحدات المباعة"}