var UserLang = {
Main_Selling_Unit:"Main selling unit",
Customers_Sales_And_Debt_Report:"Customers sales and debt report",
Symbol:"Symbol",
In_Case_Of_Invoice_Outside_The_Registered_Distribution_Areas:"In case of invoice outside the registered distribution areas",
Distribution_Area_Symbol:"Distribution area symbol",
Serial_Number_Starts_From:"Serial number starts from",
All_The_Company_Works_On_A_Single_Serial_Number_System_For_All_Distribution_Areas:"All the company works on a single serial number system for all distribution areas",
Control_Orders_Serial_Settings:"Control orders serial settings",
Direct_Exchange_Authorization_For_The_Customer:"Direct exchange authorization for the customer",
Creation_Date:"Creation date",
Excution_Date:"Excution date",
Actions_Count:"Actions count",
Vehicles_Stores_Limit_Exceeded:"Vehicles/Stores limit exceeded",
Users_Limit_Exceeded:"Users limit exceeded",
Other_Accounts:"Other accounts",
Purchase_Avg_Price:"Purchase Avg price",
Sales_Avg_Price:"Sales Avg price",
Users_Actions_Statistics_Report:"Users Actions Statistics report",
Products_Has_No_Category:"Products has no category",
Products_Transactions_Inside_The_Vehicle_Report:"Products transactions inside the vehicle store report",
Stocktaking_Inventory_Report:"Stocktaking inventory report",
Cannot_Transfer_Stock_Not_Available:"Cannot transfer stock not available",
Stock_Cannot_Be_Transferred_In_Case_The_Balance_Is_Insufficient:"Stock cannot be transferred in case the balance is insufficient",
Draft_Orders:"Draft orders",
Show_Product_Note_In_Customer_Order:"Show product note in customer order",
Product_Note:"Product note",
More_Selected_Gifts_Than_Allowed:"More selected gifts than allowed",
The_Maximum_Number_Of_Gifts_Can_Be_Chosen:"The maximum number of gifts can be chosen",
Total_Selected_Product_Count_in_Category:"Total selected product count in category",
Over_Weight:"Over weight",
Close_Customer_Order_In_Exact_Weight:"Close customer order in exact weight",
Customer_Total_Points_SMS_Message:"Customer total points sms message",
Send_SMS_To_Customer_With_Total_Points:"Send sms to customer with total points",
Customers_Points_Report:"Customers points report",
Send_Customer_Points_SMS_After_Order:"Send customer points sms after order",
Customer_Points_SMS_Message:"Customer points sms message",
Marketing_Material_Prices:"Marketing material prices",
Marketing_Materials:"Marketing materials",
Another_Executor_For_The_Order:"Another executor for the order",
Can_Change_Customer_Order_Creator:"Can change customer order creator",
Other_Mobiles_Numbers:"Other mobiles numbers",
Marketing_Messages:"Marketing messages",
The_Message_Will_Be_Sent_In_A_Name:"The message will be sent in a name",
Enter_Mobiles_Numbers:"Enter mobiles numbers",
Send_Now:"Send now",
The_Text_Of_The_Message:"The text of the message",
Marketing_Messages_To_Clients:"Marketing messages to clients",
Points_Discounted_Due_To_Return:"Points discounted due to return",
Points_Balance:"Points balance",
Initial_Points_Balance:"Initial points balance",
Total_Order_Points:"Total order points",
New_Customer_Direct_Discount:"New customer Direct_Discount",
Direct_Discount:"Direct discount",
Show_The_Product_Tax_In_The_Invoice_A_Value_Not_A_Percentage:"Show the product tax in the invoice a value, not a percentage",
Products_Sales_Report_Products_Users:"Products sales report (Products/Users)",
Select_By_Product_Category:"Select by product category",
Select_By_Product_Name:"Select by product name",
Need_To_Approval_When_Adding_New_Customer:"Need to approval when adding new customer",
Total_Assigned_Values:"Total assigned values",
Adding_Customers_Report:"Adding customers report",
Adding_New_Customers_From_Type:"Adding new customers from type",
Adding_New_Customers:"Adding new customers",
Edit_Product_Tax_In_Customer_Order:"Edit product tax in customer order ",
Final_Price:"Final price",
The_Sale_Price_Is_Lower_Than_Default_Supply_Price:"The sale price is lower than default supply price",
Cannot_Make_Order_When_Found_Scheduled_Post_Poned:"Cannot make order when found scheduled post poned",
The_Number_Per_Unit:"The number per unit",
Points:"Points",
Main_Unit:"Main unit",
Doubling:"Doubling",
The_Doubling_Number_Of_The_Main_Unit:"The doubling number of the main unit",
Add_Doubling_To_The_Main_Unit:"Add doubling to the main unit",
Total_Weights:"Total weights",
Weight:"Weight",
The_Number_To_Be_Confirmed_Received_From_Stock:"The number to be confirmed received from stock",
Confirm_Stock_Receipt:"Confirm stock receipt",
Action_Moving_Stock_Not_Completed_Need_Confirm_Received:"Action moving stock not completed . need confirm received",
Need_To_Confirm_When_Moving_Stock:"Need to confirm when moving stock",
Delayed:"Delayed",
Arabic_Plural_Groups:"مائة, ألف, مليون, مليار, تريليون, كوادريليون, كوينتليون, سكستيليون",
ArabicTwos:"مئتان, ألفان, مليونان, ملياران, تريليونان, كوادريليونان, كوينتليونان, سكستيليونان",
Arabic_Hundreds:", مائة, مئتان, ثلاثمائة, أربعمائة, خمسمائة, ستمائة, سبعمائة, ثمانمائة,تسعمائة",
Arabic_Tens:"عشرون, ثلاثون, أربعون, خمسون, ستون, سبعون, ثمانون, تسعون",
Arabic_Feminine_Ones:", إحدى, اثنتان, ثلاث, أربع, خمس, ست, سبع, ثمان, تسع,عشر, إحدى عشرة, اثنتا عشرة, ثلاث عشرة, أربع عشرة, خمس عشرة, ست عشرة, سبع عشرة, ثماني عشرة, تسع عشرة",
Arabic_Ones:", واحد, اثنان, ثلاثة, أربعة, خمسة, ستة, سبعة, ثمانية, تسعة,عشرة, أحد عشر, اثنا عشر, ثلاثة عشر, أربعة عشر, خمسة عشر, ستة عشر, سبعة عشر, ثمانية عشر, تسعة عشر",
Arabic_Suffix_Text:"لا غير.",
Arabic_Appended_Twos:"مئتا,ألفا, مليونا, مليارا, تريليونا, كوادريليونا, كوينتليونا,سكستيليونا",
Arabic_Group:"مائة, ألف,مليون, مليار, تريليون, كوادريليون, كوينتليون, سكستيليون",
Arabic_Appended_Group:", ألفاً,مليوناً, ملياراً, تريليوناً, كوادريليوناً, كوينتليوناً,سكستيليوناً",
English_Ones:"Zero, One, Two,Three, Four, Five, Six, Seven, Eight, Nine, Ten,Eleven, Twelve, Thirteen, Fourteen, Fifteen, Sixteen,Seventeen, Eighteen, Nineteen",
English_Tens:"Twenty,Thirty,Forty,Fifty,Sixty,Seventy,Eighty,Ninety",
English_Group:"Hundred,Thousand, Million, Billion, Trillion, Quadrillion,Quintillion, Sextillian, Septillion, Octillion,Nonillion, Decillion, Undecillion, Duodecillion,Tredecillion, Quattuordecillion, Quindecillion,Sexdecillion, Septendecillion, Octodecillion,Novemdecillion, Vigintillion, Unvigintillion,Duovigintillion, 10^72,10^75,10^78,10^81,10^84,10^87,Vigintinonillion,10^93,10^96,Duotrigintillion,Trestrigintillion",
English_Suffix_Text:"only.;",
Arabic_Prefix_Text:"فقط",
Egypt_Pound:"egyptPound",
Kersh:"kersh",
When_Save_Credence_Will_Add_Total_Confirmed_Discounts_In_Customer_Account:"When save credence will add total confirmed discounts in customer account",
Segment_Discount:"Segment discount",
Other_Discounts:"Other discounts",
Add_Credence_Value_To_Customer_Account:"Add credence value to customer account",
Credence_Value:"Credence value",
The_Chip_Discount_Is_Not_Calculated:"The chip discount is not calculated",
Customer_Segment_Based_On_Withdrawals_After_Tax:"Customer segment based on withdrawals after tax",
Total_Confirmed_Discounts:"Total confirmed discounts",
Customer_Withdrawals_Not_Match_Any_Segment:"Customer withdrawals not match any segment",
Tax:"Tax",
Credence_Cannot_Be_Compleated:"Credence cannot be compleated",
Last_Credences:"Last credences",
Based_On_The_Terms_Of_The_Contract:"Based on the terms of the contract",
Credence_Date:"Credence date",
Credence_Details:"Credence details",
New_Credence:"New credence",
Customer_Withdrawals_From_The_Last_Credences_Date_After_Tax_Deduction:"Customer withdrawals from the last credences date after tax deduction",
The_Date_Of_The_Last_Credenc:"The date of the last credenc",
Customer_Withdrawals_From_The_Date_Of_The_Last_Credence:"Customer withdrawals from the date of the last credence",
Credences:"Credences",
Contracts_Credences:"Contracts credences ",
Contract_Terms_Based_On_Other_Conditions:"Contract terms based on other conditions",
The_Terms_Of_The_Contract_Are_Based_On_The_Withdrawals_During_The_Period:"The terms of the contract are based on the withdrawals during the period",
Withdrawals:"Withdrawals",
Accredited_Contracts:"Accredited contracts",
Accredited_Contract:"Accredited contract",
Accredited_Contract_Details:"Accredited contract details",
Upload_Image:"Upload image",
Communicate_With_Users:"Communicate with users",
Sending_Automatic_SMS_Messages_To_Admin_When_The_Clients_Debts_Are_Due_To_Be_Paid:"Sending automatic SMS messages to admin when the clients debts are due to be paid",
Sending_Automatic_SMS_Messages_To_Users_When_The_Clients_Debts_Are_Due_To_Be_Paid_According_To_The_Track:"Sending automatic SMS messages to users when the clients debts are due to be paid according to the track",
Automatic_SMS_Sending_To_Debtor_Customers_When_Payment_Is_Due:"Automatic SMS sending to debtor customers when payment is due",
Number_To_Be_Collected_Today:"Number to be collected today",
Scheduled_Postponed:"Scheduled postponed",
subscribed_In_Actions_Module:"Subscribed in actions module",
Cannot_Make_Payments_With_Minus_Value:"Cannot make payments with minus value",
Can_Make_Payments_With_Minus_Value:"Can make payments with minus value",
Fire:"Fire",
Action_Was_Not_Implemented:"Action was not implemented",
Action_Is_Failed:"Action is failed",
Action_Is_Succeeded:"Action is succeeded",
Action_Status:"Action status",
is_Action_Succeeded:"Is action succeeded",
Must_Set_Action_Date_Time:"Must set action date time",
Previous_Balance:"Previous balance",
The_Percentage_Of_Debt_Reaching_The_Credit_Limit:"The percentage of debt reaching the credit limit",
Column_Name:"Column name",
Debtors_Customers_Report_Settings:"Debtors customers report settings",
My_Credit_Page_Settings:"My credit page settings",
Deleted_Orders:"Deleted orders",
Deleted_Payments:"Deleted payments",
Deleted_Items:"Deleted items",
Adjustments_Recorded:"Adjustments recorded",
Can_Sell_Unpriced_Product:"Can sell unpriced product",
Unpriced_Product:"Unpriced product",
Not_Enough_Stock_For_Sale:"not enough stock for sale",
Can_Make_Order_With_Negative_Stock:"Can make order with negative stock",
Control_Orders_Wayes:"Control orders wayes",
Planning_Date:"Planning date",
Item_Column_Name_Settings:"Item column name settings",
Arrange_Column:"Arrange column",
View_Column:"View column ",
Column_Name_While_Printing:"Column name while printing",
Default_Column_Name:"Default column name",
Automatic_Apply_Of_All_Invoices:"Automatic apply of all invoices",
New_Additions:"New additions",
Additions_To_The_Customer_Order:"Additions to the customer order",
Signature_While_Invoices:" Signature while invoices",
Signature_While_Payment:" Signature while payment",
SMS_Sender_Name:"SMS sender name",
Payment_Rest_Template:"Payment rest template",
Multiple:"Multiple",
CheckBox:"CheckBox",
Text:"Text",
Action_Details:"Action details",
Action_Type_Details:"Action type details",
Data_Type:"Data type",
Data:"Data",
Targeted:"Targeted",
Action_Type:"Action type",
Action_Types:"Action types",
Action:"Action",
Actions:"Actions",
Product_Prices_In_Previous_Orders:"Product prices in previous orders",
The_Maximum_Frequency_Of_The_Offer_Within_The_Invoice:"The maximum frequency of the offer within the invoice",
Add_Edite_Customers_Financial_Data:"add edite customers financial data",
Required_Supply_Delivery:"Required supply / delivery",
Required_Supply:"Required supply",
Required_Delivery:"Required delivery",
Customers_Was_Selected:"Customers was selected",
Move_Customers_To_Another_Track:"Move customers to another track",
Products_Need_To_Supply:"Products need to supply",
Tree_Branch_Details:"Tree branch details",
Branch_Inside_The_Expenses_Tree:"Branch inside the tree",
Related_To:"Related to",
Expenses_Tree:"Expenses tree",
Send_SMS_To_Debtor_Customers:"Send SMSs  to debtor customers",
Send_Custome_SMS_To_Users:"Send custome SMS to users",
Send_SMS_To_Pay_Off_Customers_Debts:"Send (SMS) to pay off customers debts",
Customer_Order_Messages:"Customer order messages",
Wrong_Mobile_Number:"Wrong mobile number",
Failed_When_Sending_SMS_Message_Please_Try_Again:"Failed when sending SMS message please try gain",
SMS_Messages_Sent_Successfully:"SMS messages sent successfully",
Send_A_Debt_Payment_Message_By_Sms_Now:"Send a debt payment message by Sms now",
Customer_Debt_Payment_Messages:"Customer debt payment messages",
SMS_Messages_Settings:"SMS messages settings",
Recalculate_Target:"Recalculate target",
My_Credit:"My credit",
Payments_Count:"Payments count",
Payments_Value:"Payments value",
Oreders_Count:"Oreders count",
Month_Sales:"Month sales",
Month:"Month",
Sent_SMSs_Report:"Sent SMSs report",
SMSs:"SMSs",
Messages_Count:"Messages count",
Send:"Send",
Message:"Message",
Add_Negative_Customer_Payment:"Add negative customer payment",
The_Advantages_Of_This_Type_Of_Customer:"The advantages of this type of customer",
Based_On_The_Total_Purchases_Of_Specific_Items_During_The_Month:"Based on the total purchases of specific items during the month",
Based_On_Total_Purchases_During_The_Month:"Based on total purchases during the month",
Conditions_And_Benefits:"Conditions and benefits",
Conditions_That_Must_Be_Met_By_The_Customer_To_Reach_This_Type:"Conditions that must be met by the customer to reach this type",
Product_Unit_Details:"Product unit details",
Product_Unit:"Product unit",
Product_Units:"Product units",
Switch_View:"Switch view",
Customers_Payments_Count:"Customers Payments count",
Current_Cash:"Current cash",
Delivery_Of_Custody_Is_Greater_Than_Available_With:"Delivery of custody is greater than available with",
Users_Custodies_Report:"User custodies report",
Please_Select_User:"Please select user",
Cannot_Transfer_Custody_To_Same_User:"Cannot transfer custody to same user",
Receiving_Custody:"Receiving custody",
Custodies:"Custodies",
Custody:"Custody",
Quantity_To_Be_Moved:"Quantity to be moved",
Customer_Received_Cash:"Customer received cash",
Fine_On_Return_Invoices:"Fine on return invoices",
Total_Refund:"Total refund",
No_Changes_To_Save:"No changes to save",
Quantity_Of_Retrun_Is_Greater_Than_Quantity_Purchased:"Quantity of retrun is greater than quantity purchased",
Quantity_Of_Retrun_From_Type:"Quantity of retrun from type",
Return_Type:"Return type",
Can_Not_Put_A_Visit_Less_Than_Minute:"Can not put a visit less than 1 minute",
Official_Working_Days_Of_The_Company:"Official working days of the company",
The_Duration_Of_The_Visit_To_The_Customer_Per_Minute:"The duration of the visit to the customer per minute",
Select_A_Day:"Select a day",
Schedule_Of_Visits:"Schedule of visits",
Affiliated_Users:"Affiliated users",
Do_You_Need_To_Continue:"Do you need to continue?",
Customer_Allready_Exist_In_Another_Track:"Customer allready exist in another track: ",
Allowance:"Allowance",
Friday:"Friday",
Thursday:"Thursday",
Wednesday:"Wednesday",
Tuesday:"Tuesday",
Monday:"Monday",
Sunday:"Sunday",
Saturday:"Saturday",
Visit_Times_From_To_Through_The_Day:"Visit times from to through the day",
Direct_Manager:"Direct manager",
The_Days_Of_The_Visit_Are_Available_To_The_Client_During_The_Week:"The number of visits during the month",
The_Number_Of_Visits_During_The_Month:"The number of visits during the month",
Custome_Visits:"Customer Visits",
Indebtedness_Less_Than:"Indebtedness less than",
Indebtedness_Greater_Than:"Indebtedness greater than",
Debtors_Customers:"Debtors customers",
Debtors_Customers_Report:"Debtors customers report",
Send_Email_To_Customer_After_Each_Invoice:"Send email to customer after each invoice",
Communicate_With_Customers_After_Each_Invoice:"Communicate with customers after each invoice",
Send_Sms_To_Customer_After_Each_Invoice:"Send sms to customer after each invoice",
Communicate_With_Customers:"Communicate with customers",
StockType:"Stock type",
StockType_Details:"Stock type details",
StockTypes:"Stock types",
Customers_Classificaions:"Customers classificaions",
Invoice_Cannote_Completed_Postponed_Balance_Reach_The_Credit_Limit_Balance:"Invoice cannot be completed Postponed balance reach the credit limit balance",
The_Client_Indebtedness_Reached_The_Credit_Limit:"The client indebtedness reached the credit limit",
Gain_Discounts_worth:"gain discounts worth",
My_Targets:"My targets",
Discounts_For_Invoice:"Discounts for invoice",
percentage:"percentage %",
Discount_Details:"Discount details",
Discounts:"Discounts",
Track_Details:"Track details",
Region_Details:"Region details",
Tracks:"Tracks",
Regions:"Regions",
Depots:"Depots",
Depot_Details:"Depot details",
Region:"Region",
Depot:"Depot",
Track:"Track",
Properties:"Properties",
Responsibility:"Responsibility",
The_Distribution_Of_Inputs_To_Staff_Is_Not_Equal_To_The_Total_Goal:"The distribution of inputs to staff is not equal to the total goal",
Full_Products_Stock_Report:"Full products stock report",
Company_Target_Details:"Company target details",
Information_About_The_Target:"Information about the Target",
Achievement_Percentage:"Achievement percentage",
Achievement:"Achievement",
Customer_Type_Details:"Customer type details",
Customer_Type:"Customer type",
Customer_Types:"Customer types",
Credit_Time:"Credit time",
Responsible:"Responsible",
Product_Category_Total_Unit_Sales:"Product category total unit sales",
Product_Units_Sales:"Product units sales",
Product_Category_Total_Sales:"Product category total sales",
Product_Total_Sales:"Product total sales",
Customer_Grade_Collected_Mony:"Customer grade collected mony",
Customer_Collected_Mony:"Customer collected mony",
Customer_Grade_Sales:"Customer grade sales",
Customer_Sales:"Customer sales",
Collected_Mony:"Collected mony",
Target_Amount_To_Be_Collected:"Target amount to be collected",
Target_Amount:"Target amount",
Target_Type:"Target type",
Target_Title:"Target title",
Company_Target:"Company target",
Company_Targets:"Company targets",
Merchandising_Material:"Merchandising material",
Merchandising_Material_Details:"Merchandising material details",
Merchandising_Materials:"Merchandising materials",
Performance:"Performance",
Offer:"Offer",
Search_For:"Search for",
Areas:"Areas",
Price_Category_Details:"Price category details",
Outlet_Classification_Details:"Outlet classification details",
Price_Categories:"Price categories",
Outlet_Classifications:"Outlet classifications",
Outlet_Classification:"Outlet classification",
Price_Category:"Price category",
Vehicles_Stores_Stock_Report_Vehicle_Store_Products:"Vehicles/Stores stock report (Vehicle-Store/Products)",
Vehicles_Stores_Stock_Detailed_Report:"Vehicles/Stores stock detailed report",
Products_Sales_Details_Report_User_Products:"Products sales details report (User/Products)",
Products_Sales_Details_Report_User_DistributionArea_Products:"Products sales details report (User/DistributionArea/Products)",
Products_Sales_Details_Report_User_Vehicle_Products:"Products sales details report (User/Vehicle/Products)",
Sold:"Sold",
Returned:"Returned",
Offers_Sales_Report:"Offers sales report",
Distributions_Area:"Distributions area",
Distribution_Area_Sales_Report:"Distribution area sales report",
Maintenance_Deadline:"Maintenance deadline",
Vehicle_Movements:"Vehicle movements",
Less:"Less",
More:"More",
Has_Earned:"Has earned",
Orders_That_Have_Benefited_From_The_Offer:"Orders that have benefited from the offer",
Information_About_The_Offer:"Information about the offer",
Conditions_To_Be_Eligible_For_The_Offer:"Conditions to be eligible for the offer",
Offer_Priority:"Offer priority",
Total_Invoice_Inside_Offer:"Total invoice inside offer",
Invalid_Customer_Signature:"Invalid customer signature",
Please_Enter_Customer_Signature:"Please enter customer signature",
Offer_For_Invoice:"Offer for invoice",
Total_Order_And_Discount:"Total order & discount",
Selected_Products:"Selected products",
Recalculate_Source_Balanace:"Recalculate source balanace",
Recalculate_Customer_Balanace:"Recalculate customer balanace",
Total_Order_Price:"Total order price",
Warning_There_Is_A_Duplicate_Product_In_This_Invoice_Do_You_Wish_To_Continue:"WARNING, there is a duplicate product in this invoice, do you wish to continue?",
Warning_There_Is_One_Or_More_Products_Without_A_Price_Do_You_Wish_To_Continue:"WARNING, there is one or more products without a price, do you wish to continue?",
Frequency_Offer:"Frequency_Offer",
Total_Order_Discount_Precentage:"Total_Order_Discount_Precentage",
Total_Order_Discount_Value:"Total_Order_Discount_Value",
Free_Additional_Products:"Free_Additional_Products",
Discount_On_Products:"Discount_On_Products",
Additional_Gifts:"Additional_Gifts",
Gifts:"Gifts",
Conditions:"Conditions",
Exact_Customer:"Exact_Customer",
Offer_Type:"Offer_Type",
End_Date:"End_Date",
Start_Date:"Start_Date",
Supplies_Detail:"Supplies_Detail",
Distribution_Area_Details:"Distribution_Area_Details",
Distribution_Areas:"Distribution areas",
Distribution_Area:"Distribution area",
Orders_Detail:"Orders detail",
Order_Detail:"Order detail",
Sales_Target:"Sales target",
Marketing:"Marketing",
Sales:"Sales",
Governovate:"Governovate",
Neighborhood:"Neighborhood",
City:"City",
Invoices_Only_By_Location:"Invoices only by location",
Customer_Signature:"Customer signature",
Payments:"Payments",
Edit_Offer:"Edit offer",
Offer_Details:"Offer details",
New_Offer:"New offer",
Offers:"Offers",
Number:"Number",
Monitoring_Board:"Monitoring board",
Stock:"Stock",
Store:"Store",
Vehicle:"Vehicle",
Allowed_Vehicles_Stores:"Allowed vehicles/stores",
Category_Search:"Category search",
Product_Category_Stock_Report:"Product category stock report",
Categories:"Categories",
Product_Category_Profitability_Report:"Product profitability report",
Product_Profitability_Report:"Product profitability report",
Product_Store_Profitability_Report:"Product/Store profitability report",
Highest_Sold_Count_Products:"Highest sold count products",
Highest_Sold_Price_Products:"Highest sold price products",
Difference:"Difference",
Order_By:"Order by",
Highest_Sold_Products:"Highest sold products",
Add_Return:"Add return",
Product_Category_Valuation_Report:"Product category valuation report",
Customers_Orders:"Customers orders",
Sources_Supplies:"Sources supplies",
Merge:"Merge info",
Total_Profit:"Total profit",
Products_Statistics:"Products statistics",
Total_Orders_Price:"Total orders price",
Total_Supplies_Price:"Total supplies price",
Sold_Units_Count:"Sold units count",
Bought_Units_Count:"Bought units count",
Products_Count:"Products count",
Is_Dual:"Is dual SIM",
Storage:"Storage (GB)",
Processor:"Processor",
OS:"OS",
Color:"Color",
Battery:"Battery (mAh)",
RAM:"RAM (GB)",
Screen_Size:"Screen size (inches)",
Back_Camera:"Main camera (MP)",
Front_Camera:"Front camera (MP)",
Cash_Customer_Bill:"Cash customer bill",
Cash_Customer:"Cash customer",
Google_Plus:"Google+",
Twitter:"Twitter",
Facebook:"Facebook",
Social_Media_Marketing:"Social media marketing",
Copy:"Copy",
Add:"Add",
Default_Supply_Price:"Default supply price",
Fast_Add:"Fast add",
View:"View",
Permisions:"Permisions",
Edit_Order_Products_Prices:"Edit Order's products prices",
Hide_Prices_Print:"Hide prices in print",
Product_Type:"Product type",
Notifications_Settings:"Notifications settings",
Customers_Notifications:"Customers notifications",
Users_Notifications:"Users notifications",
Sources_Notifications:"Sources notifications",
Products_Notifications:"Products notifications",
Vehicles_Stores_Notifications:"Vehicles/Stores notifications",
Product_Vehicles_Stores_Notifications:"Product vehicles/stores notifications",
Customer_Orders_Notifications:"Customer orders notifications",
Source_Supplies_Notifications:"Source supplies notifications",
Customer_Payements_Notifications:"Customer payements notifications",
Source_Payments_Notifications:"Source payments notifications",
Expenses_Notifications:"Expenses notifications",
Product_Minimum_Qauntity_Supply_Notifications:"Minimum qauntity for supply notifications",
Product_Orders:"Product orders",
Product_Supplies:"Product supplies",
Vehicle_Store_Selection_Is_Required:"Vehicle/Store selection is required",
Old_Password:"Old password",
Not_Valid:"Not valid",
New_Password:"New password",
And:"And",
Or:"Or",
Not_Equal:"Not equal",
Change_Password:"Change password",
Admin:"Admin",
Is_Mandatory:"Is mandatory",
Are_You_Sure_Save_These_Products_Data:"Are you sure save these products data?",
Minimum_Qauntity_For_Supply_Data_Is_Not_Digits:"Minimum qauntity for supply data aren't digits",
System_Colors:"System colors",
Are_You_Sure_Save_These_Customers_Data:"Are you sure for saving these customers data?",
Are_You_Sure_Save_These_Sources_Data:"Are you sure for saving these Sources data?",
Initial_Balance_Data_Is_Not_Digits:"Initial balance data aren't digits",
Customer_Grade_Data_Is_Not_Valid:"Customer grade data isn't valid",
Please_Select_One_Row_At_Least:"Please select one row at least",
Already_Exist:"Already exist",
The_Maximum_Data_Submitted_Are_500_Rows_Per_File:"The maximum data submitted are 500 rows per file",
Notice:"Notice",
Add_To_Customer_Order:"Add to customer order",
Add_To_Source_Supply:"Add to Source supply",
Address:"Address",
Alerts:"Alerts",
All:"All",
All_Customers:"All customers",
All_Products:"All products",
All_Sources:"All Sources",
Are_You_Sure_Delete:"ARE YOU SURE? Delete Action Can Not Be Undo.",
Balance:"Balance:",
Barcode:"Barcode",
Calculate:"Calculate",
Can_Not_Be_Deleted:"Can't be deleted",
Cancel:"Cancel",
Category:"Category",
Chart:"Chart",
Code:"Code",
Company_Settings:"Company settings",
Confirm:"Confirm",
Confirm_Password:"Confirm Password",
Confirmed_Visits:"Confirmed Visits",
Count:"Count",
Customer:"Customer",
Customer_Details:"Customer details",
User_Details:"User details",
Customer_Financial_Data:"Customer financial data",
Customer_Financial_Summary:"Customer Financial Summary",
Customer_Grade_Sales_Report:"Customer grade sales report",
Customer_Not_Defined:"Customer not defined",
Customer_Order_Report:"Customers orders report",
Products_In_Customer_Orders_Report:"Products in customer orders report",
Customer_Order_Template:"Customer order template",
Customer_Orders:"Customer Orders",
Customer_Orders_Filters:"Customer Orders Filters",
Customer_Payments:"Customer payments",
Customer_Sales_Report:"Customer sales report",
Customers:"Customers",
Customers_Payments:"Customers payments",
Customers_Payments_Report:"Customers payments report",
Customers_Report:"Customers Report",
Customers_Search:"Customers Search",
Customers_Orders_Search:"Customers orders search",
Daily:"Daily",
Dashboard:"Dashboard",
Data_Selection:"Data selection",
Data_Upload:"Data upload",
Date:"Date",
Delete:"Delete",
Deleted:"Deleted",
Description:"Description",
Details:"Details",
Discount:"Discount",
Does_Not_Exist:"Does not exist",
Edit:"Edit",
Edit_Customer_Info:"Edit Customer Info",
Edit_Source_Info:"Edit Source Info",
Edit_User:"Edit User",
Email:"Email",
Expense:"Expense",
Expense_Types:"Expense Types:",
Expenses:"Expenses",
Expenses_Report:"Expenses report",
Export:"Export",
File_No:"File No",
File_No_Allready_Exist:"File No Already Exist",
File_Selection:"File selection",
File_Upload:"File upload",
Files:"Files",
Search:"Search",
Finance:"Finance",
Financial_Data:"Financial Data",
Financial_Report:"Financial Report",
From:"From",
From_Vehicle_Store:"From vehicle/store",
Full_Access:"Full Access",
Full_Name:"Full Name",
Go_Back:"Go Back",
Grade:"Grade",
Has_Product:"Has Product",
Help:"Help",
HR:"HR",
Image:"Image",
Initial_Balance:"Initial balance",
Invalid_User_Name_Or_Password:"invalid user name or password",
Stocktaking:"Stocktaking",
Inventory:"Inventory",
Invoices:"Invoices",
Item:"Item",
Job:"Job",
Language:"Language",
Loading_User_Data:"Loading user data",
Location:"Location",
Credit_Limit:"Credit limit",
Logo:"Logo",
logout:"logout",
Main_Info:"Main Info",
Main_User_Data:"Main User Data",
Manufacturer_Part_Number:"Man Part #",
Minimum_Qauntity_For_Supply:"Minimum qauntity for supply",
Mobile:"Mobile",
Monthly:"Monthly",
More_Info:"More Info",
My_Account:"My Account",
Name:"Name",
Name_Already_Exist:"Name already exist",
New_Customer:"New Customer",
New_Customer_Payment:"New customer payment",
New_Expenses:"New Expenses",
New_Order:"New customer order",
New_Payment:"New Payment",
New_Product:"New Product",
New_Supply:"New Supply",
New_Stock_Movement:"New stock movement",
New_Vehicle_Store:"New Vehicle/Store",
New_Source:"New Source",
New_Source_Payment:"New Source payment",
New_User:"New user",
Next:"Next",
No:"NO",
No_Data_Found:"No Data Found..",
Notes:"Notes",
Nothing_To_Search_For:"Nothing To Search For",
Orders:"Orders",
Orders_Count:"Orders Count",
Orders_Report:"Orders Report",
Paid:"Paid",
Password:"Password",
Password_Is_Not_Confirmed:"Password Is Not Confirmed",
Password_Must_Be_At_Least_4_Characters_Or_Letters:"Password Must Be At Least 4 Characters Or Letters",
Payee:"Payee",
Payments_Balance_Report:"Payments balance report",
Please_Add_A_Content:"Please Add A Content",
Please_Add_A_Name:"Please Add A Name",
Please_Add_A_Name_Price_And_Date:"Please Add A Name, Price And Date",
Please_Add_A_Username:"Please Add A Username",
Please_Review_Date_Input:"Please review date input ",
Please_Add_A_Valid_Birthdate:"Please Add A Valid BirthDate",
Please_Add_A_Valid_Password:"Please Add A Valid Password",
Please_Complete_The_Inputs:"Please complete the inputs",
Please_Define_A_Valid_Date_Range:"Please Define A Valid Date Range",
Please_Select_A_Product:"Please select a product",
Please_Select_A_Quantity:"Please select a quantity",
Please_Select_A_Vehicle_Store:"Please select a vehicle/store",
Postponed:"credit",
Prepaid:"Prepaid",
Previous:"Previous",
Price:"Price",
Price_A:"Price A",
Price_B:"Price B",
Price_C:"Price C",
Price_D:"Price D",
Price_E:"Price E",
Price_Grades:"Price grades",
Prices:"Prices",
Prices_Offer_List:"prices offer list",
Print:"Print",
Print_Preview:"Print Preview",
Printing_Settings:"Printing settings",
Prints:"Prints",
Product_Category_Sales_Supplies_Report:"Product category sales, supplies report",
Product_Details:"Product details",
Product_Inventory:"Product inventory",
Product_Inventory_Report:"Product inventory Report",
Product_Location:"Product location",
Product_Name:"Product name",
Product_Sales_Supplies_Report:"Product sales, supplies report",
Product_Search:"Product search",
Products:"Products",
Vehicles_Stores_Has_Products:"Vehicles/Stores has products",
Products_Report:"Products Report",
Products_Without_Barcode:"Products without barcode",
Products_Without_Category:"Products without category",
Products_Without_Min_Quantity:"Products without min quantity",
Products_Without_Price:"Products without price",
Products_Without_Stock:"Products without stock",
Profit_Report:"Profit report",
Supply:"Supply",
Supplies_Count:"Supplies count",
Supplies_Report:"Supplies Report",
Quantity:"Quantity",
Recent_Searchs:"Recent Searchs",
Redirecting:"redirecting...",
Report_Is_Ready:"Report Is Ready",
Reports:"Reports",
Sales_And_Supply:"Sales and supply",
Save:"Save",
Save_Account_Data:"Save Account Data",
Save_Draft:"Save draft",
Save_Expense_Data:"Save Expense Data",
Save_Print:"Save & Print",
Save_Print_Template_Data:"Save & Print Template Data",
Saved:"Saved",
Saved_Template:"Saved Template",
Saving:"Saving",
Search_By_Name_File_No_Address_Job_Mobile_Gender_Etc:"Search By Name, File No, Address, Job, Mobile, Gender, Etc..",
Searching:"Searching",
Select_A_Date_For_This_Visit:"Select A Date For This Visit",
Select_A_Date_In_The_Future:"Select A Date In The Future",
Serial:"Serial",
Serial_Prices_Are_Required:"Serial & Prices are required",
Settings:"Settings",
Shipment:"Shipment",
Soon:"Soon",
Start_Hour:"Start Hour",
Statistics:"Statistics",
Status:"Status",
Stock_Lots:"Stock Lots",
Stock_Movement:"Stock Movement",
Stock_Movement_Filters:"Stock movement filters",
Stock_Settings:"Stock Settings",
Vehicle_Store_Details:"Vehicle/Store details",
Vehicle_Store_Name:"Vehicle/Store name",
Vehicle_Store_Products:"Vehicle/Store Products",
Vehicle_Store_Sales_Supplies_Report:"Vehicle/Store sales, supplies report",
Vehicle_Store_Valuation_Report:"Vehicle/Store valuation report",
Vehicles_Stores:"Vehicles/Stores",
Vehicle_Store:"Vehicle/Store",
Vehicles_Stores_Search:"Vehicles/Stores Search",
Summary:"Summary",
Source:"Source",
Source_Details:"Source details",
Source_Financial_Data:"Source financial data",
Source_Financial_Summary:"Source Financial Summary",
Source_Not_Defined:"Source_Not_Defined",
Source_Payments:"Source payments",
Source_Supplies_Report:"Source Supplies report",
Source_Supply_Template:"Source supply template",
Source_Supplies:"Source Supplies",
Source_Supplies_Filters:"Source Supplies Filters",
Sources:"Sources",
Sources_Payments:"Sources payments",
Sources_Payments_Report:"Sources payments report",
Sources_Prices_Offers:"Sources prices offers",
Sources_Supplies_Report:"Sources supplies report",
Sources_Report:"Sources Report",
Sources_Search:"Sources Search",
Template:"Template",
Template_Contents:"Template Contents",
Template_Keys:"Template Keys",
Time:"Time",
To:"To",
To_Vehicle_Store:"To Vehicle/Store",
Total:"Total",
Total_Customers_Payments:"Total customers payments",
Total_Expenses:"Total expenses",
Total_Price:"Total Price",
Total_Sources_Payments:"Total Sources payments",
Type:"Type",
Unit:"Unit",
Units:"Units",
Update_Customer:"Update Customer",
Update_Expense:"Update expense",
Update_Product:"Update product",
Update_Product_Inventory:"Update product inventory",
Update_Product_Prices:"Update product prices",
Update_Vehicle_Store:"Update Vehicle/Store",
Update_Source:"Update Source",
Update_User:"Update user",
Uploading:"Uploading",
User_Name:"User Name",
User_Privileges:"User Privileges",
User_Sales_Supplies_Report:"User sales, supplies report",
Users:"Users",
User:"User",
Users_Search:"Users search",
Users_Settings:"Users settings",
Value:"Value",
Value_Can_Not_Be_More_Than:"Value can not be more than",
Value_Can_Not_Be_Zero_Or_Negative:"Value can not be zero or negative",
Welcome:"Welcome :",
Working_Please_Wait:"working please wait...",
Yes:"YES",
You_Can_Not_Move_Stock_From_The_Same_Vehicle_Store:"You can not move stock from the same vehicle/Store",
You_Don_T_Have_A_Privileges_To_Access_This_Section:"You Do not Have A Privileges To Access This Section",
Hierarchy:"Hierarchy",
Visit_Day:"Visit day",
Cost_Price:"Cost price",
Contracts:"Contracts",
Contract:"Contract",
Contract_Details:"Contract details",
Period:"Period",
Segment:"Segment",
Segments:"Segments",
New_Segment:"New segment",
Segment_Details:"Segment details",
Cash:"Cash",
Invoice_Segment:"Invoice segment",
Pay_In_Cash:"Pay In Cash",
Id:"Serial",
no_condition:"No Conditions",
Not_Applicable:"Not Applicable",
Monthely_Customer_Purchases:"Monthely Customer Purchases",
Contract_Terms:"Contract Terms",
New_Contract:"New Contract",
Due_Date:"Due Date",
Total_Invoice_Before_Discounts:"Total Price Before Discounts",
Total_Offers_Discounts:"Total Offers Discounts",
Total_Discounts_amount:"Total Disounts Amount",
Total_Segments_Discounts:"Total Segments Discounts",
Discount_Not_Applied:"discount not applied due to condition not met",
Now:"Now",
Mid_Year:"Mid Year",
End_Year:"End Of Year",
Our_Prouducts:"Our Prouducts Only",
Minimum_Sales_Month:"Minimum Monthely Sales ",
Periodical_Monthley_Sales:"Periodical Monthely Sales",
Total_Instant_Discounts_From_Contracts:"Total Instant Discounts From Contracts",
Quarter:"Quarter",
Send_Customer_Financial_Report_Via_SMS:"send customer financial reportvia SMS",
Are_You_Sure:"Are you sure",
Invalid_Customer_Mobile_Number:"Invalid customer mobile number",
First_Supply_Price:"First supply price",
Last_Supply_Price:"Last supply price",
Min_Supply_Price:"Min supply price",
Max_Supply_Price:"Max supply price",
Supplies_Items_Count:"Supplies items count",
First_Order_Price:"First order price",
Last_Order_Price:"Last order price",
Min_Order_Price:"Min order price",
Max_Order_Price:"Max order price",
Orders_Items_Count:"Orders items count"}